/** Vendor pinned upstream SVGs and provenance into the offline icon bundle. */
import { mkdir, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
const version = "1.13.1";
const names = [
  "house-door-fill",
  "airplane-fill",
  "briefcase-fill",
  "linkedin",
  "github",
  "medium",
  "envelope-fill",
  "translate",
  "palette-fill",
  "chevron-double-left",
  "chat-dots-fill",
  "list",
  "x-lg",
  "pause-fill",
  "play-fill",
  "arrow-counterclockwise",
  "arrow-up-right",
  "arrow-down-right",
  "arrow-right",
  "arrow-up",
  "plus-circle-dotted",
  "plus-lg",
  "dash-lg",
  "check-lg",
  "braces-asterisk",
  "award-fill",
  "building-fill",
  "mortarboard-fill",
];
const root = new URL("../src/", import.meta.url);
const directory = new URL("assets/icons/bootstrap/", root);
await mkdir(directory, { recursive: true });
const source = `https://raw.githubusercontent.com/twbs/icons/v${version}/`;
/** Fetch an upstream source asset and fail before accepting an HTTP error body. */
async function download(path) {
  const response = await fetch(source + path);
  if (!response.ok) throw new Error(`${path}: ${response.status}`);
  return response.text();
}
const icons = Object.fromEntries(
  await Promise.all(
    names.map(async (name) => {
      const svg = await download(`icons/${name}.svg`);
      await writeFile(new URL(`${name}.svg`, directory), svg);
      return [
        name,
        svg.slice(svg.indexOf(">") + 1, svg.lastIndexOf("</svg>")).trim(),
      ];
    }),
  ),
);
await writeFile(new URL("LICENSE", directory), await download("LICENSE"));
await writeFile(
  new URL("SOURCES.json", directory),
  JSON.stringify(
    { package: "bootstrap-icons", version, source, icons: names },
    null,
    2,
  ) + "\n",
);
await writeFile(
  new URL("core/icons.js", root),
  `// Bootstrap Icons ${version}, MIT. Generated by scripts/vendor-icons.mjs. No runtime requests.
(() => {
 const paths = ${JSON.stringify(icons, null, 2)};
 /** Render a trusted local icon by its registered Bootstrap name. */
 function svg(name, className = '') {
  if (!Object.hasOwn(paths, name)) throw new Error('Unknown icon: ' + name);
  return '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" fill="currentColor" class="bi bi-' + name + ' ' + className + '" aria-hidden="true" focusable="false">' + paths[name] + '</svg>';
 }
 /** Populate declarative icon placeholders in newly created markup. */
 function mount(root = document) {
  root.querySelectorAll('[data-icon]').forEach(element => { element.innerHTML = svg(element.dataset.icon); });
 }
 window.Icons = Object.freeze({ svg, mount });
 mount();
})();
`,
);
console.log(
  `Vendored ${names.length} Bootstrap Icons ${version} into ${fileURLToPath(directory)}`,
);
